---
- hosts:
    - localhost
  gather_facts: true

  roles:
    - role: alacritty
      tags: alacritty

    - role: tmux
      tags: tmux

    - role: zsh
      tags: zsh

    - role: fzf
      tags: fzf

    - role: neovim
      tags: neovim
