---
- hosts: localhost
  gather_facts: true

  roles:
    - role: common
      tags: common

    - role: alacritty
      tags: alacritty

    - role: tmux
      tags: tmux

    - role: zsh
      tags: zsh

    - role: neovim
      tags: neovim
