require('config.general')
require('config.buffers')
require('config.windows')
require('config.whitespace')
require('config.colorcolumn')
require('config.filetype')
require('config.indentation')
require('config.statusline')
