---
- name: Create Zsh config directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ zsh_config_dir }}"
    - "{{ zsh_plugins_dir }}"
    - "{{ zsh_external_dir }}"

- name: Copy Zsh config
  template:
    src: "config/{{ item.path }}"
    dest: "{{ zsh_config_dir }}/{{ item.path | regex_replace('.j2', '') }}"
    mode: preserve
  with_filetree: ../templates/config
  when: item.state == 'file'
  register: config

- name: Copy main Zsh config
  template:
    src: "{{ item }}"
    dest: "{{ dotfiles_home }}/{{ item | regex_replace('.j2', '') }}"
  with_items:
    - .zshrc.j2
    - .zshenv

- name: Change default shell
  become: true
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items: "{{ zsh_users }}"
