---
- name: Install Antigen
  get_url:
    url: "{{ zsh_antigen_url }}"
    dest: "{{ zsh_plugins_dir }}/antigen.zsh"
  register: antigen

- name: Install Zsh plugins
  shell: "zsh -c {{ zsh_config_dir }}/plugins.zsh"
  when: config.changed or antigen.changed