---
- name: Install tmux
  community.general.homebrew:
    name: tmux
    state: present
  when: dotfiles_distribution == "MacOSX"

- name: Create tmux config directory
  file:
    path: "{{ dotfiles_tmux.config_dir }}"
    state: directory

- name: Copy main tmux config
  template:
    src: .tmux.conf.j2
    dest: "{{ dotfiles_home }}/.tmux.conf"

- name: Copy tmux config
  template:
    src: "config/{{ item.path }}"
    dest: "{{ dotfiles_tmux.config_dir }}/{{ item.path | regex_replace('.j2', '') }}"
    mode: preserve
  with_filetree: ../templates/config
  when: item.state == 'file'
