---
- name: Install Alacritty
  community.general.homebrew_cask:
    name: alacritty
    state: present
  when: dotfiles_distribution == "MacOSX"

- name: Create Alacritty config directory
  file:
    path: "{{ dotfiles_alacritty.config_dir }}"
    state: directory

- name: Copy Alacritty config
  template:
    src: alacritty.yaml.j2
    dest: "{{ dotfiles_alacritty.config_dir }}/alacritty.yml"
