---
- name: Install Neovim
  community.general.homebrew:
    name: neovim
    state: present
  when: dotfiles_distribution == "MacOSX"

- name: Install Neovim
  become: true
  ansible.builtin.apt:
    name: neovim
    state: present
  when: dotfiles_distribution == "Debian"

- name: Create Neovim config directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dotfiles_neovim.config_dir }}"
    - "{{ dotfiles_neovim.config_dir }}/lua"
    - "{{ dotfiles_neovim.config_dir }}/lua/config"
    - "{{ dotfiles_neovim.config_dir }}/lua/plugins"
    - "{{ dotfiles_neovim.config_dir }}/lua/plugins/lsp"

- name: Copy Neovim config
  template:
    src: "{{ item.path }}"
    dest: "{{ dotfiles_neovim.config_dir }}/{{ item.path | regex_replace('.j2', '') }}"
    mode: preserve
  with_filetree: ../templates
  when: item.state == 'file'
